# Generated by Django 3.0 on 2019-12-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('color', models.CharField(max_length=250)),
                ('cats_or_dogs', models.CharField(max_length=250)),
            ],
        ),
    ]
